apiVersion: batch/v1
kind: Job
metadata:
  name: web-content-loader
spec:
  template:
    spec:
      containers:
      - name: file-loader
        image: busybox
        command: [ "sh", "-c", "echo '<h1>Hello from Minikube!</h1>' > 
/mnt/website/index.html && sleep 10" ]
        volumeMounts:
        - name: web-content
          mountPath: /mnt/website
      restartPolicy: Never
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: web-content-pvc
  backoffLimit: 0

