apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # You can choose a different port if needed

